swagger: "2.0"
info:
  title: Casa do Código Service
  description: Casa do Código HTTP service
  version: ""
host: localhost:3333
consumes:
- application/json
- application/xml
- application/gob
produces:
- application/json
- application/xml
- application/gob
paths:
  /actors:
    post:
      tags:
      - catalog
      summary: create_actor catalog
      operationId: catalog#create_actor
      parameters:
      - name: create_actor_request_body
        in: body
        required: true
        schema:
          $ref: '#/definitions/CatalogCreateActorRequestBody'
          required:
          - name
          - email
          - description
      responses:
        "201":
          description: Created response.
          schema:
            $ref: '#/definitions/CatalogCreateActorResponseBody'
            required:
            - id
            - name
            - email
            - description
            - created_at
        "400":
          description: Bad Request response.
          schema:
            $ref: '#/definitions/CatalogCreateActorInvalidFieldsResponseBody'
      schemes:
      - http
  /actors/{id}:
    get:
      tags:
      - catalog
      summary: show_actor catalog
      operationId: catalog#show_actor
      parameters:
      - name: id
        in: path
        description: ID
        required: true
        type: string
      responses:
        "200":
          description: OK response.
          schema:
            $ref: '#/definitions/CatalogShowActorResponseBody'
            required:
            - id
            - name
            - email
            - description
            - created_at
        "404":
          description: Not Found response.
          schema:
            $ref: '#/definitions/CatalogShowActorNotFoundResponseBody'
      schemes:
      - http
  /books:
    get:
      tags:
      - catalog
      summary: list_books catalog
      operationId: catalog#list_books
      responses:
        "200":
          description: OK response.
          schema:
            type: array
            items:
              $ref: '#/definitions/BookDTOResponse'
      schemes:
      - http
    post:
      tags:
      - catalog
      summary: create_book catalog
      operationId: catalog#create_book
      parameters:
      - name: create_book_request_body
        in: body
        required: true
        schema:
          $ref: '#/definitions/CatalogCreateBookRequestBody'
          required:
          - title
          - synopsis
          - price
          - pages
          - isbn
          - issue
          - category_ids
          - actor_ids
      responses:
        "201":
          description: Created response.
          schema:
            $ref: '#/definitions/CatalogCreateBookResponseBody'
            required:
            - id
            - title
            - synopsis
            - price
            - pages
            - isbn
            - issue
            - category_ids
            - actor_ids
        "400":
          description: Bad Request response.
          schema:
            $ref: '#/definitions/CatalogCreateBookInvalidFieldsResponseBody'
      schemes:
      - http
  /books/{id}:
    get:
      tags:
      - catalog
      summary: show_book catalog
      operationId: catalog#show_book
      parameters:
      - name: id
        in: path
        description: ID
        required: true
        type: string
      responses:
        "200":
          description: OK response.
          schema:
            $ref: '#/definitions/CatalogShowBookResponseBody'
            required:
            - id
            - title
            - synopsis
            - price
            - pages
            - isbn
            - issue
            - category_ids
            - actor_ids
        "404":
          description: Not Found response.
          schema:
            $ref: '#/definitions/CatalogShowBookNotFoundResponseBody'
      schemes:
      - http
  /carts:
    post:
      tags:
      - catalog
      summary: create_cart catalog
      operationId: catalog#create_cart
      parameters:
      - name: create_cart_request_body
        in: body
        required: true
        schema:
          $ref: '#/definitions/CatalogCreateCartRequestBody'
          required:
          - total
          - items
          - customer_id
      responses:
        "201":
          description: Created response.
          schema:
            $ref: '#/definitions/CatalogCreateCartResponseBody'
            required:
            - id
            - total
            - items
            - customer_id
        "400":
          description: Bad Request response.
          schema:
            $ref: '#/definitions/CatalogCreateCartInvalidFieldsResponseBody'
      schemes:
      - http
  /categories:
    post:
      tags:
      - catalog
      summary: create_category catalog
      operationId: catalog#create_category
      parameters:
      - name: create_category_request_body
        in: body
        required: true
        schema:
          $ref: '#/definitions/CatalogCreateCategoryRequestBody'
          required:
          - name
      responses:
        "201":
          description: Created response.
          schema:
            $ref: '#/definitions/CatalogCreateCategoryResponseBody'
            required:
            - id
            - name
        "400":
          description: Bad Request response.
          schema:
            $ref: '#/definitions/CatalogCreateCategoryInvalidFieldsResponseBody'
      schemes:
      - http
  /categories/{id}:
    get:
      tags:
      - catalog
      summary: show_category catalog
      operationId: catalog#show_category
      parameters:
      - name: id
        in: path
        description: ID
        required: true
        type: string
      responses:
        "200":
          description: OK response.
          schema:
            $ref: '#/definitions/CatalogShowCategoryResponseBody'
            required:
            - id
            - name
        "404":
          description: Not Found response.
          schema:
            $ref: '#/definitions/CatalogShowCategoryNotFoundResponseBody'
      schemes:
      - http
  /countries:
    post:
      tags:
      - catalog
      summary: create_country catalog
      operationId: catalog#create_country
      parameters:
      - name: create_country_request_body
        in: body
        required: true
        schema:
          $ref: '#/definitions/CatalogCreateCountryRequestBody'
          required:
          - name
      responses:
        "201":
          description: Created response.
          schema:
            $ref: '#/definitions/CatalogCreateCountryResponseBody'
            required:
            - id
            - name
        "400":
          description: Bad Request response.
          schema:
            $ref: '#/definitions/CatalogCreateCountryInvalidFieldsResponseBody'
      schemes:
      - http
  /customers:
    post:
      tags:
      - catalog
      summary: create_customer catalog
      operationId: catalog#create_customer
      parameters:
      - name: create_customer_request_body
        in: body
        required: true
        schema:
          $ref: '#/definitions/CatalogCreateCustomerRequestBody'
          required:
          - first_name
          - last_name
          - email
          - document
          - address
          - phone
      responses:
        "201":
          description: Created response.
          schema:
            $ref: '#/definitions/CatalogCreateCustomerResponseBody'
            required:
            - id
            - first_name
            - last_name
            - email
            - document
            - address
            - phone
        "400":
          description: Bad Request response.
          schema:
            $ref: '#/definitions/CatalogCreateCustomerInvalidFieldsResponseBody'
      schemes:
      - http
  /states:
    post:
      tags:
      - catalog
      summary: create_state catalog
      operationId: catalog#create_state
      parameters:
      - name: create_state_request_body
        in: body
        required: true
        schema:
          $ref: '#/definitions/CatalogCreateStateRequestBody'
          required:
          - name
          - country_id
      responses:
        "201":
          description: Created response.
          schema:
            $ref: '#/definitions/CatalogCreateStateResponseBody'
            required:
            - id
            - name
            - country_id
        "400":
          description: Bad Request response.
          schema:
            $ref: '#/definitions/CatalogCreateStateInvalidFieldsResponseBody'
      schemes:
      - http
  /swagger.json:
    get:
      tags:
      - swagger
      summary: Download ../../gen/http/openapi.json
      operationId: swagger#/swagger.json
      responses:
        "200":
          description: File downloaded
          schema:
            type: file
      schemes:
      - http
definitions:
  AddressDTORequestBody:
    title: AddressDTORequestBody
    type: object
    properties:
      address:
        type: string
        example: Iste nesciunt.
      cep:
        type: string
        example: Deleniti magnam facilis voluptatem.
      city:
        type: string
        example: Vel nemo est odio nostrum.
      complement:
        type: string
        example: Neque et at.
      country_id:
        type: string
        example: Veniam et.
      state_id:
        type: string
        example: Sit porro illum.
    description: Address Type
    example:
      address: Doloribus voluptatum.
      cep: Dolores quis.
      city: Nemo qui voluptatum eos.
      complement: In accusantium.
      country_id: Commodi exercitationem id eligendi deserunt.
      state_id: Eos dolorum ea.
    required:
    - address
    - complement
    - city
    - country_id
    - state_id
    - cep
  AddressDTOResponseBody:
    title: AddressDTOResponseBody
    type: object
    properties:
      address:
        type: string
        example: Voluptas ex architecto quam.
      cep:
        type: string
        example: Ut quos culpa et laudantium.
      city:
        type: string
        example: Rerum maxime.
      complement:
        type: string
        example: Reiciendis ut sit totam.
      country_id:
        type: string
        example: Deleniti ad voluptas et ipsa dolore eaque.
      state_id:
        type: string
        example: Nihil officia et aut dolores.
    description: Address Type
    example:
      address: Non possimus enim.
      cep: Quibusdam aliquid saepe.
      city: Aut maxime sapiente ducimus est ipsum.
      complement: Rem velit.
      country_id: Et ipsum ullam.
      state_id: Rem et placeat et.
    required:
    - address
    - complement
    - city
    - country_id
    - state_id
    - cep
  BookDTOResponse:
    title: BookDTOResponse
    type: object
    properties:
      actor_ids:
        type: array
        items:
          type: string
          example: Quia dolores voluptas cumque iure et.
        example:
        - Quidem delectus maiores culpa praesentium.
        - Omnis neque autem quas tempore suscipit est.
        - Qui cupiditate repellat.
      category_ids:
        type: array
        items:
          type: string
          example: Corrupti deserunt sint et illum.
        example:
        - Explicabo perferendis quos quis.
        - Sint ut qui incidunt minus voluptates.
        - Voluptatem ipsum inventore omnis omnis officiis voluptatem.
        - Optio maxime voluptatem distinctio velit delectus et.
      id:
        type: string
        example: Ducimus facere iusto ipsam.
      isbn:
        type: string
        example: Necessitatibus omnis repellat error nemo est.
      issue:
        type: string
        example: Similique quasi deleniti et natus.
      pages:
        type: integer
        example: 4770033921065430718
        minimum: 100
      price:
        type: number
        example: 20.683641
        minimum: 20
      summary:
        type: string
        example: Quia eos.
      synopsis:
        type: string
        example: ynh
        maxLength: 500
      title:
        type: string
        example: Illo odio ducimus et.
    description: Book Type
    example:
      actor_ids:
      - Sed quidem dolorem.
      - Eos velit provident laborum dolorem fugiat natus.
      - Illo sapiente.
      category_ids:
      - Veritatis totam fugiat repellendus minus accusamus iste.
      - Est facere saepe et nobis officia.
      - Sunt repellendus qui voluptate.
      id: Ea esse aspernatur placeat eius et.
      isbn: Dolor non.
      issue: Necessitatibus nobis quod facere ut deserunt.
      pages: 3121884051991030980
      price: 20.859055
      summary: Veritatis quia laborum non et quibusdam veritatis.
      synopsis: 34b
      title: Et quia a iste et qui sapiente.
    required:
    - id
    - title
    - synopsis
    - price
    - pages
    - isbn
    - issue
    - category_ids
    - actor_ids
  CatalogCreateActorInvalidFieldsResponseBody:
    title: 'Mediatype identifier: application/vnd.goa.error; view=default'
    type: object
    properties:
      fault:
        type: boolean
        description: Is the error a server-side fault?
        example: false
      id:
        type: string
        description: ID is a unique identifier for this particular occurrence of the problem.
        example: 123abc
      message:
        type: string
        description: Message is a human-readable explanation specific to this occurrence of the problem.
        example: parameter 'p' must be an integer
      name:
        type: string
        description: Name is the name of this class of errors.
        example: bad_request
      temporary:
        type: boolean
        description: Is the error temporary?
        example: true
      timeout:
        type: boolean
        description: Is the error a timeout?
        example: false
    description: create_actor_invalid_fields_response_body result type (default view)
    example:
      fault: true
      id: 123abc
      message: parameter 'p' must be an integer
      name: bad_request
      temporary: false
      timeout: true
    required:
    - name
    - id
    - message
    - temporary
    - timeout
    - fault
  CatalogCreateActorRequestBody:
    title: CatalogCreateActorRequestBody
    type: object
    properties:
      description:
        type: string
        example: on8
        maxLength: 400
      email:
        type: string
        example: sandrine.cronin@lindhane.com
        format: email
      name:
        type: string
        example: Eaque fugiat eos aut suscipit.
    example:
      description: mfe
      email: herminia_rath@willms.com
      name: Blanditiis necessitatibus rerum modi.
    required:
    - name
    - email
    - description
  CatalogCreateActorResponseBody:
    title: CatalogCreateActorResponseBody
    type: object
    properties:
      created_at:
        type: string
        example: Nulla soluta.
      description:
        type: string
        example: 7gt
        maxLength: 400
      email:
        type: string
        example: eldora_crooks@kundewisozk.info
        format: email
      id:
        type: string
        example: Dolores qui doloremque provident id ut tenetur.
      name:
        type: string
        example: Perspiciatis et ducimus.
    example:
      created_at: Non sit dolor velit provident inventore.
      description: t7o
      email: brenden@sauerfadel.com
      id: Dolore explicabo et molestias et.
      name: Culpa alias voluptate facere.
    required:
    - id
    - name
    - email
    - description
    - created_at
  CatalogCreateBookInvalidFieldsResponseBody:
    title: 'Mediatype identifier: application/vnd.goa.error; view=default'
    type: object
    properties:
      fault:
        type: boolean
        description: Is the error a server-side fault?
        example: false
      id:
        type: string
        description: ID is a unique identifier for this particular occurrence of the problem.
        example: 123abc
      message:
        type: string
        description: Message is a human-readable explanation specific to this occurrence of the problem.
        example: parameter 'p' must be an integer
      name:
        type: string
        description: Name is the name of this class of errors.
        example: bad_request
      temporary:
        type: boolean
        description: Is the error temporary?
        example: false
      timeout:
        type: boolean
        description: Is the error a timeout?
        example: false
    description: create_book_invalid_fields_response_body result type (default view)
    example:
      fault: true
      id: 123abc
      message: parameter 'p' must be an integer
      name: bad_request
      temporary: true
      timeout: true
    required:
    - name
    - id
    - message
    - temporary
    - timeout
    - fault
  CatalogCreateBookRequestBody:
    title: CatalogCreateBookRequestBody
    type: object
    properties:
      actor_ids:
        type: array
        items:
          type: string
          example: Alias iusto.
        example:
        - Quisquam non est illum doloremque ut.
        - Quasi est modi minima eaque ab.
        - Qui consectetur.
      category_ids:
        type: array
        items:
          type: string
          example: Quaerat pariatur.
        example:
        - Eaque eveniet consequuntur.
        - Suscipit quos.
      isbn:
        type: string
        example: Cumque labore.
      issue:
        type: string
        example: Earum magnam quia.
      pages:
        type: integer
        example: 4707753284748452151
        minimum: 100
      price:
        type: number
        example: 20.964495
        minimum: 20
      summary:
        type: string
        example: Illo blanditiis corporis eum exercitationem temporibus.
      synopsis:
        type: string
        example: x62
        maxLength: 500
      title:
        type: string
        example: Et illum tempora.
    example:
      actor_ids:
      - Voluptatibus voluptatibus inventore vitae eos.
      - Ab aut quia necessitatibus odio esse.
      category_ids:
      - Ut cum aut earum et tempora.
      - Dolorem minus harum eligendi nemo ut consectetur.
      - Ea nisi iusto ipsa totam exercitationem veritatis.
      isbn: Ipsum omnis est.
      issue: Sit aliquam ut.
      pages: 3100972448739441450
      price: 20.777239
      summary: Sed error.
      synopsis: j7k
      title: Suscipit qui.
    required:
    - title
    - synopsis
    - price
    - pages
    - isbn
    - issue
    - category_ids
    - actor_ids
  CatalogCreateBookResponseBody:
    title: CatalogCreateBookResponseBody
    type: object
    properties:
      actor_ids:
        type: array
        items:
          type: string
          example: Quia non sed et.
        example:
        - Est dolores occaecati.
        - Autem beatae maxime blanditiis.
        - Voluptas porro labore aut atque.
      category_ids:
        type: array
        items:
          type: string
          example: Magni ab.
        example:
        - Aspernatur nisi et.
        - A qui consequatur enim culpa odit quibusdam.
        - Iusto facere eius aliquam cum.
        - Quia perspiciatis eaque aut ducimus.
      id:
        type: string
        example: Eos molestiae.
      isbn:
        type: string
        example: Architecto totam labore.
      issue:
        type: string
        example: Sit ipsum vel quibusdam.
      pages:
        type: integer
        example: 7197182930786664069
        minimum: 100
      price:
        type: number
        example: 20.778069
        minimum: 20
      summary:
        type: string
        example: Aut ut.
      synopsis:
        type: string
        example: iyd
        maxLength: 500
      title:
        type: string
        example: Id adipisci aut aut.
    example:
      actor_ids:
      - Eum provident qui error aut a dolore.
      - Cupiditate laudantium molestias totam.
      category_ids:
      - Aspernatur ipsa rerum dolor magni sunt et.
      - Nihil accusamus incidunt saepe mollitia consequatur quia.
      - Ut est atque.
      - Perspiciatis reiciendis.
      id: Similique eaque omnis nemo sapiente.
      isbn: Voluptatem nulla distinctio repudiandae et dolorem.
      issue: Ut unde est ab dolor libero.
      pages: 1715134913681643687
      price: 20.239958
      summary: Quod quia.
      synopsis: uy8
      title: Laborum omnis quia consequatur exercitationem sed.
    required:
    - id
    - title
    - synopsis
    - price
    - pages
    - isbn
    - issue
    - category_ids
    - actor_ids
  CatalogCreateCartInvalidFieldsResponseBody:
    title: 'Mediatype identifier: application/vnd.goa.error; view=default'
    type: object
    properties:
      fault:
        type: boolean
        description: Is the error a server-side fault?
        example: true
      id:
        type: string
        description: ID is a unique identifier for this particular occurrence of the problem.
        example: 123abc
      message:
        type: string
        description: Message is a human-readable explanation specific to this occurrence of the problem.
        example: parameter 'p' must be an integer
      name:
        type: string
        description: Name is the name of this class of errors.
        example: bad_request
      temporary:
        type: boolean
        description: Is the error temporary?
        example: true
      timeout:
        type: boolean
        description: Is the error a timeout?
        example: true
    description: create_cart_invalid_fields_response_body result type (default view)
    example:
      fault: false
      id: 123abc
      message: parameter 'p' must be an integer
      name: bad_request
      temporary: true
      timeout: true
    required:
    - name
    - id
    - message
    - temporary
    - timeout
    - fault
  CatalogCreateCartRequestBody:
    title: CatalogCreateCartRequestBody
    type: object
    properties:
      customer_id:
        type: string
        example: Alias animi inventore ab libero odio dolore.
      items:
        type: array
        items:
          $ref: '#/definitions/ItemDTORequestBody'
        example:
        - amount: 1131047539
          book_id: Corporis maiores labore autem occaecati eligendi fugit.
        - amount: 1131047539
          book_id: Corporis maiores labore autem occaecati eligendi fugit.
      total:
        type: number
        example: 0.5475538
        format: float
    example:
      customer_id: Esse incidunt possimus tempore.
      items:
      - amount: 1131047539
        book_id: Corporis maiores labore autem occaecati eligendi fugit.
      - amount: 1131047539
        book_id: Corporis maiores labore autem occaecati eligendi fugit.
      - amount: 1131047539
        book_id: Corporis maiores labore autem occaecati eligendi fugit.
      total: 0.76867527
    required:
    - total
    - items
    - customer_id
  CatalogCreateCartResponseBody:
    title: CatalogCreateCartResponseBody
    type: object
    properties:
      customer_id:
        type: string
        example: Nihil totam.
      id:
        type: string
        example: Dignissimos voluptas aut ipsum repudiandae vel.
      items:
        type: array
        items:
          $ref: '#/definitions/ItemDTOResponseBody'
        example:
        - amount: 745111911
          book_id: Quos aut aliquid.
        - amount: 745111911
          book_id: Quos aut aliquid.
        - amount: 745111911
          book_id: Quos aut aliquid.
        - amount: 745111911
          book_id: Quos aut aliquid.
      total:
        type: number
        example: 0.85854334
        format: float
    example:
      customer_id: Quae dignissimos debitis magni.
      id: Enim eum quisquam.
      items:
      - amount: 745111911
        book_id: Quos aut aliquid.
      - amount: 745111911
        book_id: Quos aut aliquid.
      - amount: 745111911
        book_id: Quos aut aliquid.
      - amount: 745111911
        book_id: Quos aut aliquid.
      total: 0.23985867
    required:
    - id
    - total
    - items
    - customer_id
  CatalogCreateCategoryInvalidFieldsResponseBody:
    title: 'Mediatype identifier: application/vnd.goa.error; view=default'
    type: object
    properties:
      fault:
        type: boolean
        description: Is the error a server-side fault?
        example: true
      id:
        type: string
        description: ID is a unique identifier for this particular occurrence of the problem.
        example: 123abc
      message:
        type: string
        description: Message is a human-readable explanation specific to this occurrence of the problem.
        example: parameter 'p' must be an integer
      name:
        type: string
        description: Name is the name of this class of errors.
        example: bad_request
      temporary:
        type: boolean
        description: Is the error temporary?
        example: false
      timeout:
        type: boolean
        description: Is the error a timeout?
        example: true
    description: create_category_invalid_fields_response_body result type (default view)
    example:
      fault: true
      id: 123abc
      message: parameter 'p' must be an integer
      name: bad_request
      temporary: true
      timeout: false
    required:
    - name
    - id
    - message
    - temporary
    - timeout
    - fault
  CatalogCreateCategoryRequestBody:
    title: CatalogCreateCategoryRequestBody
    type: object
    properties:
      name:
        type: string
        example: Blanditiis et dolorum voluptatibus consequuntur.
    example:
      name: Laborum quam.
    required:
    - name
  CatalogCreateCategoryResponseBody:
    title: CatalogCreateCategoryResponseBody
    type: object
    properties:
      id:
        type: string
        example: Cupiditate unde qui officiis maiores eum in.
      name:
        type: string
        example: Reprehenderit saepe aliquid ratione est nostrum.
    example:
      id: Id quo quos ea.
      name: Non voluptates quia temporibus rerum atque sint.
    required:
    - id
    - name
  CatalogCreateCountryInvalidFieldsResponseBody:
    title: 'Mediatype identifier: application/vnd.goa.error; view=default'
    type: object
    properties:
      fault:
        type: boolean
        description: Is the error a server-side fault?
        example: true
      id:
        type: string
        description: ID is a unique identifier for this particular occurrence of the problem.
        example: 123abc
      message:
        type: string
        description: Message is a human-readable explanation specific to this occurrence of the problem.
        example: parameter 'p' must be an integer
      name:
        type: string
        description: Name is the name of this class of errors.
        example: bad_request
      temporary:
        type: boolean
        description: Is the error temporary?
        example: true
      timeout:
        type: boolean
        description: Is the error a timeout?
        example: false
    description: create_country_invalid_fields_response_body result type (default view)
    example:
      fault: false
      id: 123abc
      message: parameter 'p' must be an integer
      name: bad_request
      temporary: true
      timeout: false
    required:
    - name
    - id
    - message
    - temporary
    - timeout
    - fault
  CatalogCreateCountryRequestBody:
    title: CatalogCreateCountryRequestBody
    type: object
    properties:
      name:
        type: string
        example: Assumenda quibusdam qui sed tenetur libero.
    example:
      name: Autem quas qui aliquam.
    required:
    - name
  CatalogCreateCountryResponseBody:
    title: CatalogCreateCountryResponseBody
    type: object
    properties:
      id:
        type: string
        example: Vel nihil voluptatibus dolores.
      name:
        type: string
        example: Doloribus facilis voluptas est omnis laborum.
      state_ids:
        type: string
        example: Asperiores vel qui molestiae rerum maiores.
    example:
      id: Distinctio autem est vel mollitia.
      name: Odio voluptatem aut nostrum est.
      state_ids: Ratione voluptatum repudiandae.
    required:
    - id
    - name
  CatalogCreateCustomerInvalidFieldsResponseBody:
    title: 'Mediatype identifier: application/vnd.goa.error; view=default'
    type: object
    properties:
      fault:
        type: boolean
        description: Is the error a server-side fault?
        example: true
      id:
        type: string
        description: ID is a unique identifier for this particular occurrence of the problem.
        example: 123abc
      message:
        type: string
        description: Message is a human-readable explanation specific to this occurrence of the problem.
        example: parameter 'p' must be an integer
      name:
        type: string
        description: Name is the name of this class of errors.
        example: bad_request
      temporary:
        type: boolean
        description: Is the error temporary?
        example: true
      timeout:
        type: boolean
        description: Is the error a timeout?
        example: false
    description: create_customer_invalid_fields_response_body result type (default view)
    example:
      fault: false
      id: 123abc
      message: parameter 'p' must be an integer
      name: bad_request
      temporary: true
      timeout: true
    required:
    - name
    - id
    - message
    - temporary
    - timeout
    - fault
  CatalogCreateCustomerRequestBody:
    title: CatalogCreateCustomerRequestBody
    type: object
    properties:
      address:
        $ref: '#/definitions/AddressDTORequestBody'
      cart_ids:
        type: array
        items:
          type: string
          example: Quidem doloremque adipisci.
        example:
        - Et dolorem.
        - Eligendi facilis cumque quos veritatis recusandae quae.
      document:
        type: string
        example: Incidunt enim blanditiis sapiente voluptas molestiae consectetur.
      email:
        type: string
        example: linnie@harveysmitham.com
        format: email
      first_name:
        type: string
        example: Iusto quia.
      last_name:
        type: string
        example: Cum illum saepe consequatur accusantium.
      phone:
        type: string
        example: Doloremque a et.
    example:
      address:
        address: Recusandae occaecati animi.
        cep: Quis fugit corporis aliquid beatae sequi.
        city: Placeat sit et est atque.
        complement: Et vitae.
        country_id: Rem consectetur quo voluptate.
        state_id: Earum esse enim doloremque.
      cart_ids:
      - Nisi est asperiores magnam laborum.
      - Dolor doloremque omnis ullam.
      - Et non dicta quos.
      document: Ducimus vel inventore at est molestiae.
      email: esta_dooley@bogan.org
      first_name: Eius qui rerum ut earum.
      last_name: Et non voluptates.
      phone: Sed magni tenetur eveniet.
    required:
    - first_name
    - last_name
    - email
    - document
    - address
    - phone
  CatalogCreateCustomerResponseBody:
    title: CatalogCreateCustomerResponseBody
    type: object
    properties:
      address:
        $ref: '#/definitions/AddressDTOResponseBody'
      cart_ids:
        type: array
        items:
          type: string
          example: Voluptates adipisci natus est commodi totam eaque.
        example:
        - Pariatur amet quidem.
        - Dolores minus omnis.
        - Eos omnis ullam at rem.
        - Aut rem fugiat.
      document:
        type: string
        example: Dolorem qui.
      email:
        type: string
        example: hulda@hudson.info
        format: email
      first_name:
        type: string
        example: Ut quia.
      id:
        type: string
        example: Earum enim.
      last_name:
        type: string
        example: Perspiciatis autem unde accusantium fugiat.
      phone:
        type: string
        example: Nostrum suscipit minus omnis quae eos cumque.
    example:
      address:
        address: Quisquam dolorem nobis totam.
        cep: Dolorem soluta fugiat deleniti nobis quam.
        city: Qui inventore eligendi tenetur dolores provident.
        complement: Autem accusantium.
        country_id: Eos quos.
        state_id: Expedita corrupti.
      cart_ids:
      - Labore omnis minus nihil nihil accusantium.
      - Dolor non consequatur modi omnis eligendi temporibus.
      - Eius qui tempora ab dolor.
      document: Quae quae modi sint.
      email: jaiden@breitenbergwillms.info
      first_name: Id aspernatur fuga laudantium repellendus recusandae eum.
      id: Dignissimos ut repellendus.
      last_name: Est consequuntur eos pariatur eos nesciunt.
      phone: Dignissimos sit eaque natus omnis.
    required:
    - id
    - first_name
    - last_name
    - email
    - document
    - address
    - phone
  CatalogCreateStateInvalidFieldsResponseBody:
    title: 'Mediatype identifier: application/vnd.goa.error; view=default'
    type: object
    properties:
      fault:
        type: boolean
        description: Is the error a server-side fault?
        example: false
      id:
        type: string
        description: ID is a unique identifier for this particular occurrence of the problem.
        example: 123abc
      message:
        type: string
        description: Message is a human-readable explanation specific to this occurrence of the problem.
        example: parameter 'p' must be an integer
      name:
        type: string
        description: Name is the name of this class of errors.
        example: bad_request
      temporary:
        type: boolean
        description: Is the error temporary?
        example: true
      timeout:
        type: boolean
        description: Is the error a timeout?
        example: false
    description: create_state_invalid_fields_response_body result type (default view)
    example:
      fault: false
      id: 123abc
      message: parameter 'p' must be an integer
      name: bad_request
      temporary: true
      timeout: true
    required:
    - name
    - id
    - message
    - temporary
    - timeout
    - fault
  CatalogCreateStateRequestBody:
    title: CatalogCreateStateRequestBody
    type: object
    properties:
      country_id:
        type: string
        example: In et sequi.
      name:
        type: string
        example: Ut ut et eum est.
    example:
      country_id: Enim quia at quaerat culpa est consequatur.
      name: Voluptas autem.
    required:
    - name
    - country_id
  CatalogCreateStateResponseBody:
    title: CatalogCreateStateResponseBody
    type: object
    properties:
      country_id:
        type: string
        example: Molestias saepe iusto consequuntur eius minima voluptas.
      id:
        type: string
        example: Culpa est beatae nobis libero.
      name:
        type: string
        example: Incidunt maiores reiciendis eveniet est est laudantium.
    example:
      country_id: Quidem inventore non et velit.
      id: Et laudantium nihil ut incidunt illo laudantium.
      name: Possimus libero optio corrupti optio quos.
    required:
    - id
    - name
    - country_id
  CatalogShowActorNotFoundResponseBody:
    title: 'Mediatype identifier: application/vnd.goa.error; view=default'
    type: object
    properties:
      fault:
        type: boolean
        description: Is the error a server-side fault?
        example: false
      id:
        type: string
        description: ID is a unique identifier for this particular occurrence of the problem.
        example: 123abc
      message:
        type: string
        description: Message is a human-readable explanation specific to this occurrence of the problem.
        example: parameter 'p' must be an integer
      name:
        type: string
        description: Name is the name of this class of errors.
        example: bad_request
      temporary:
        type: boolean
        description: Is the error temporary?
        example: true
      timeout:
        type: boolean
        description: Is the error a timeout?
        example: false
    description: show_actor_not_found_response_body result type (default view)
    example:
      fault: true
      id: 123abc
      message: parameter 'p' must be an integer
      name: bad_request
      temporary: true
      timeout: false
    required:
    - name
    - id
    - message
    - temporary
    - timeout
    - fault
  CatalogShowActorResponseBody:
    title: CatalogShowActorResponseBody
    type: object
    properties:
      created_at:
        type: string
        example: Est minus dolorum.
      description:
        type: string
        example: ak8
        maxLength: 400
      email:
        type: string
        example: reed@wintheiserstoltenberg.org
        format: email
      id:
        type: string
        example: Praesentium sint molestias officiis voluptates animi quasi.
      name:
        type: string
        example: Dolorum alias nostrum vero odio et.
    example:
      created_at: Sit repellendus temporibus ut repellat quo.
      description: 1nx
      email: palma.schiller@cassin.biz
      id: Et alias amet molestiae.
      name: Doloribus modi impedit.
    required:
    - id
    - name
    - email
    - description
    - created_at
  CatalogShowBookNotFoundResponseBody:
    title: 'Mediatype identifier: application/vnd.goa.error; view=default'
    type: object
    properties:
      fault:
        type: boolean
        description: Is the error a server-side fault?
        example: false
      id:
        type: string
        description: ID is a unique identifier for this particular occurrence of the problem.
        example: 123abc
      message:
        type: string
        description: Message is a human-readable explanation specific to this occurrence of the problem.
        example: parameter 'p' must be an integer
      name:
        type: string
        description: Name is the name of this class of errors.
        example: bad_request
      temporary:
        type: boolean
        description: Is the error temporary?
        example: false
      timeout:
        type: boolean
        description: Is the error a timeout?
        example: false
    description: show_book_not_found_response_body result type (default view)
    example:
      fault: true
      id: 123abc
      message: parameter 'p' must be an integer
      name: bad_request
      temporary: false
      timeout: false
    required:
    - name
    - id
    - message
    - temporary
    - timeout
    - fault
  CatalogShowBookResponseBody:
    title: CatalogShowBookResponseBody
    type: object
    properties:
      actor_ids:
        type: array
        items:
          type: string
          example: Totam nam dolore rerum ad quia asperiores.
        example:
        - Labore sapiente similique rerum autem a.
        - Omnis expedita eligendi sit et et est.
        - Doloremque sint.
        - Id amet et.
      category_ids:
        type: array
        items:
          type: string
          example: Sed eveniet alias ut.
        example:
        - In porro nisi nemo qui illo sed.
        - Qui laboriosam sunt itaque.
        - Omnis ipsa.
        - Dolor saepe ullam dolores et.
      id:
        type: string
        example: Et nulla maxime deserunt rerum voluptas et.
      isbn:
        type: string
        example: Fugit quod ea.
      issue:
        type: string
        example: Occaecati aut ducimus et.
      pages:
        type: integer
        example: 3493031391116913427
        minimum: 100
      price:
        type: number
        example: 20.185472
        minimum: 20
      summary:
        type: string
        example: Quas qui.
      synopsis:
        type: string
        example: 4sr
        maxLength: 500
      title:
        type: string
        example: Ut temporibus sint ducimus iusto deserunt.
    example:
      actor_ids:
      - Quo aliquid.
      - Nisi accusantium.
      - Velit voluptatem.
      category_ids:
      - Ex vero vero aut sint.
      - Est ut.
      - Aut eum itaque natus voluptatem quia consequatur.
      id: Assumenda fugiat.
      isbn: Qui deleniti quia.
      issue: Facilis laborum consequatur quia.
      pages: 5330182430394185733
      price: 20.81489
      summary: Nesciunt voluptatibus explicabo assumenda quo voluptatem voluptate.
      synopsis: 58m
      title: Neque eius a atque.
    required:
    - id
    - title
    - synopsis
    - price
    - pages
    - isbn
    - issue
    - category_ids
    - actor_ids
  CatalogShowCategoryNotFoundResponseBody:
    title: 'Mediatype identifier: application/vnd.goa.error; view=default'
    type: object
    properties:
      fault:
        type: boolean
        description: Is the error a server-side fault?
        example: false
      id:
        type: string
        description: ID is a unique identifier for this particular occurrence of the problem.
        example: 123abc
      message:
        type: string
        description: Message is a human-readable explanation specific to this occurrence of the problem.
        example: parameter 'p' must be an integer
      name:
        type: string
        description: Name is the name of this class of errors.
        example: bad_request
      temporary:
        type: boolean
        description: Is the error temporary?
        example: false
      timeout:
        type: boolean
        description: Is the error a timeout?
        example: true
    description: show_category_not_found_response_body result type (default view)
    example:
      fault: true
      id: 123abc
      message: parameter 'p' must be an integer
      name: bad_request
      temporary: false
      timeout: true
    required:
    - name
    - id
    - message
    - temporary
    - timeout
    - fault
  CatalogShowCategoryResponseBody:
    title: CatalogShowCategoryResponseBody
    type: object
    properties:
      id:
        type: string
        example: Explicabo quisquam.
      name:
        type: string
        example: Est tenetur dolorem tempora illum doloremque quia.
    example:
      id: Quidem accusantium cumque voluptatem et.
      name: Facilis sequi dolore officia molestiae vel sed.
    required:
    - id
    - name
  ItemDTORequestBody:
    title: ItemDTORequestBody
    type: object
    properties:
      amount:
        type: integer
        example: 1495453910
        format: int32
      book_id:
        type: string
        example: Quis et molestiae neque laboriosam perferendis.
    description: Item Type
    example:
      amount: 757922866
      book_id: Unde voluptas veritatis beatae.
    required:
    - book_id
    - amount
  ItemDTOResponseBody:
    title: ItemDTOResponseBody
    type: object
    properties:
      amount:
        type: integer
        example: 1356730870
        format: int32
      book_id:
        type: string
        example: Provident ut.
    description: Item Type
    example:
      amount: 1335746935
      book_id: Maiores et officia.
    required:
    - book_id
    - amount
