openapi: 3.0.3
info:
  title: Casa do Código Service
  description: Casa do Código HTTP service
  version: "1.0"
servers:
- url: http://localhost:3333
  description: hosts for Casa do Código Service.
paths:
  /actors:
    post:
      tags:
      - catalog
      summary: create_actor catalog
      operationId: catalog#create_actor
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateActorRequestBody'
            example:
              description: df5
              email: boris@boehm.net
              name: Quis fuga voluptas dolorum.
      responses:
        "201":
          description: ""
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ActorDTO'
              example:
                created_at: Error provident dolorem tempore expedita rerum.
                description: sin
                email: ruby@kuvalis.info
                id: Labore recusandae sit.
                name: Vel dolor molestiae doloremque quisquam dolorem.
        "400":
          description: ""
          content:
            application/vnd.goa.error:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                fault: false
                id: 123abc
                message: parameter 'p' must be an integer
                name: bad_request
                temporary: false
                timeout: true
  /actors/{id}:
    get:
      tags:
      - catalog
      summary: show_actor catalog
      operationId: catalog#show_actor
      parameters:
      - name: id
        in: path
        description: ID
        required: true
        schema:
          type: string
          description: ID
          example: Est et voluptatem.
        example: Quidem sit illo aut incidunt.
      responses:
        "200":
          description: ""
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ActorDTO'
              example:
                created_at: A expedita illo ut perferendis.
                description: 6zv
                email: vinnie@kling.biz
                id: Dolores aut omnis occaecati quia aperiam nisi.
                name: Exercitationem eos autem corporis dolores.
        "404":
          description: ""
          content:
            application/vnd.goa.error:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                fault: false
                id: 123abc
                message: parameter 'p' must be an integer
                name: bad_request
                temporary: true
                timeout: true
  /books:
    get:
      tags:
      - catalog
      summary: list_books catalog
      operationId: catalog#list_books
      responses:
        "200":
          description: ""
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/BookDTO'
                example:
                - actor_ids:
                  - Eum aut eos aut.
                  - Ab perferendis voluptatibus error ullam natus.
                  - Molestiae ipsam totam quia quae aut hic.
                  - Quis nobis.
                  category_ids:
                  - Quis aut iste qui possimus sunt eum.
                  - Sit recusandae laudantium iste eum libero voluptatum.
                  - Placeat molestiae.
                  id: Dolor iste qui aspernatur velit nobis.
                  isbn: Odit impedit fugiat itaque cum.
                  issue: Quisquam sint at et minima est et.
                  pages: 3692961263830674922
                  price: 20.471115
                  summary: Voluptas velit eligendi.
                  synopsis: gbx
                  title: Dolores dolor officia quaerat error autem harum.
                - actor_ids:
                  - Eum aut eos aut.
                  - Ab perferendis voluptatibus error ullam natus.
                  - Molestiae ipsam totam quia quae aut hic.
                  - Quis nobis.
                  category_ids:
                  - Quis aut iste qui possimus sunt eum.
                  - Sit recusandae laudantium iste eum libero voluptatum.
                  - Placeat molestiae.
                  id: Dolor iste qui aspernatur velit nobis.
                  isbn: Odit impedit fugiat itaque cum.
                  issue: Quisquam sint at et minima est et.
                  pages: 3692961263830674922
                  price: 20.471115
                  summary: Voluptas velit eligendi.
                  synopsis: gbx
                  title: Dolores dolor officia quaerat error autem harum.
                - actor_ids:
                  - Eum aut eos aut.
                  - Ab perferendis voluptatibus error ullam natus.
                  - Molestiae ipsam totam quia quae aut hic.
                  - Quis nobis.
                  category_ids:
                  - Quis aut iste qui possimus sunt eum.
                  - Sit recusandae laudantium iste eum libero voluptatum.
                  - Placeat molestiae.
                  id: Dolor iste qui aspernatur velit nobis.
                  isbn: Odit impedit fugiat itaque cum.
                  issue: Quisquam sint at et minima est et.
                  pages: 3692961263830674922
                  price: 20.471115
                  summary: Voluptas velit eligendi.
                  synopsis: gbx
                  title: Dolores dolor officia quaerat error autem harum.
                - actor_ids:
                  - Eum aut eos aut.
                  - Ab perferendis voluptatibus error ullam natus.
                  - Molestiae ipsam totam quia quae aut hic.
                  - Quis nobis.
                  category_ids:
                  - Quis aut iste qui possimus sunt eum.
                  - Sit recusandae laudantium iste eum libero voluptatum.
                  - Placeat molestiae.
                  id: Dolor iste qui aspernatur velit nobis.
                  isbn: Odit impedit fugiat itaque cum.
                  issue: Quisquam sint at et minima est et.
                  pages: 3692961263830674922
                  price: 20.471115
                  summary: Voluptas velit eligendi.
                  synopsis: gbx
                  title: Dolores dolor officia quaerat error autem harum.
              example:
              - actor_ids:
                - Eum aut eos aut.
                - Ab perferendis voluptatibus error ullam natus.
                - Molestiae ipsam totam quia quae aut hic.
                - Quis nobis.
                category_ids:
                - Quis aut iste qui possimus sunt eum.
                - Sit recusandae laudantium iste eum libero voluptatum.
                - Placeat molestiae.
                id: Dolor iste qui aspernatur velit nobis.
                isbn: Odit impedit fugiat itaque cum.
                issue: Quisquam sint at et minima est et.
                pages: 3692961263830674922
                price: 20.471115
                summary: Voluptas velit eligendi.
                synopsis: gbx
                title: Dolores dolor officia quaerat error autem harum.
              - actor_ids:
                - Eum aut eos aut.
                - Ab perferendis voluptatibus error ullam natus.
                - Molestiae ipsam totam quia quae aut hic.
                - Quis nobis.
                category_ids:
                - Quis aut iste qui possimus sunt eum.
                - Sit recusandae laudantium iste eum libero voluptatum.
                - Placeat molestiae.
                id: Dolor iste qui aspernatur velit nobis.
                isbn: Odit impedit fugiat itaque cum.
                issue: Quisquam sint at et minima est et.
                pages: 3692961263830674922
                price: 20.471115
                summary: Voluptas velit eligendi.
                synopsis: gbx
                title: Dolores dolor officia quaerat error autem harum.
              - actor_ids:
                - Eum aut eos aut.
                - Ab perferendis voluptatibus error ullam natus.
                - Molestiae ipsam totam quia quae aut hic.
                - Quis nobis.
                category_ids:
                - Quis aut iste qui possimus sunt eum.
                - Sit recusandae laudantium iste eum libero voluptatum.
                - Placeat molestiae.
                id: Dolor iste qui aspernatur velit nobis.
                isbn: Odit impedit fugiat itaque cum.
                issue: Quisquam sint at et minima est et.
                pages: 3692961263830674922
                price: 20.471115
                summary: Voluptas velit eligendi.
                synopsis: gbx
                title: Dolores dolor officia quaerat error autem harum.
              - actor_ids:
                - Eum aut eos aut.
                - Ab perferendis voluptatibus error ullam natus.
                - Molestiae ipsam totam quia quae aut hic.
                - Quis nobis.
                category_ids:
                - Quis aut iste qui possimus sunt eum.
                - Sit recusandae laudantium iste eum libero voluptatum.
                - Placeat molestiae.
                id: Dolor iste qui aspernatur velit nobis.
                isbn: Odit impedit fugiat itaque cum.
                issue: Quisquam sint at et minima est et.
                pages: 3692961263830674922
                price: 20.471115
                summary: Voluptas velit eligendi.
                synopsis: gbx
                title: Dolores dolor officia quaerat error autem harum.
    post:
      tags:
      - catalog
      summary: create_book catalog
      operationId: catalog#create_book
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateBookRequestBody'
            example:
              actor_ids:
              - In autem eum.
              - Ab veritatis officiis accusamus quibusdam aut eum.
              category_ids:
              - Assumenda dolor quia et dolore.
              - Incidunt ipsum rerum quia ducimus voluptatum.
              - Dignissimos et occaecati dolorem.
              - Eum sit est.
              isbn: Et ut provident at hic.
              issue: Sint et.
              pages: 8812144099905341790
              price: 20.14946
              summary: Magnam et necessitatibus impedit quam.
              synopsis: vwd
              title: Sequi aliquid sed.
      responses:
        "201":
          description: ""
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BookDTO'
              example:
                actor_ids:
                - Accusantium ipsa commodi corporis excepturi.
                - Necessitatibus ab mollitia.
                - Porro quis explicabo sit.
                - Eum odit aspernatur a.
                category_ids:
                - Tempora alias quis.
                - Qui fugit ut praesentium.
                - Hic est soluta.
                id: Dolor quia aliquam aliquid ullam facere.
                isbn: Perferendis adipisci excepturi qui qui repellat dolor.
                issue: Fugiat distinctio iusto corporis eum.
                pages: 4724853152887151523
                price: 20.799353
                summary: Et quasi harum nam.
                synopsis: 66i
                title: Cupiditate consectetur.
        "400":
          description: ""
          content:
            application/vnd.goa.error:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                fault: true
                id: 123abc
                message: parameter 'p' must be an integer
                name: bad_request
                temporary: false
                timeout: false
  /books/{id}:
    get:
      tags:
      - catalog
      summary: show_book catalog
      operationId: catalog#show_book
      parameters:
      - name: id
        in: path
        description: ID
        required: true
        schema:
          type: string
          description: ID
          example: Non ad ipsam libero rerum eaque.
        example: Commodi itaque.
      responses:
        "200":
          description: ""
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BookDTO'
              example:
                actor_ids:
                - Voluptate voluptatem veniam laudantium.
                - Vero nam.
                category_ids:
                - Officia eum veritatis nam est qui.
                - Rerum commodi.
                id: Esse laboriosam asperiores et quo.
                isbn: Non fuga reprehenderit aut sequi.
                issue: Quasi voluptatum.
                pages: 8084748301012457223
                price: 20.72649
                summary: Ea officiis voluptatem est.
                synopsis: k3d
                title: Eum consequatur rem sunt voluptates sed amet.
        "404":
          description: ""
          content:
            application/vnd.goa.error:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                fault: false
                id: 123abc
                message: parameter 'p' must be an integer
                name: bad_request
                temporary: true
                timeout: false
  /carts:
    post:
      tags:
      - catalog
      summary: create_cart catalog
      operationId: catalog#create_cart
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateCartRequestBody'
            example:
              customer_id: Iusto nihil cupiditate voluptatem ut ut corporis.
              items:
              - amount: 1682166100
                book_id: Occaecati quibusdam non.
              - amount: 1682166100
                book_id: Occaecati quibusdam non.
              - amount: 1682166100
                book_id: Occaecati quibusdam non.
              - amount: 1682166100
                book_id: Occaecati quibusdam non.
              total: 0.49038583
      responses:
        "201":
          description: ""
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CartDTO'
              example:
                customer_id: Omnis non nam veritatis corrupti sit delectus.
                id: Quo sed qui.
                items:
                - amount: 1496435812
                  book_id: Ut doloremque doloremque at nemo pariatur.
                - amount: 1496435812
                  book_id: Ut doloremque doloremque at nemo pariatur.
                - amount: 1496435812
                  book_id: Ut doloremque doloremque at nemo pariatur.
                total: 0.12400658
        "400":
          description: ""
          content:
            application/vnd.goa.error:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                fault: true
                id: 123abc
                message: parameter 'p' must be an integer
                name: bad_request
                temporary: true
                timeout: true
  /categories:
    post:
      tags:
      - catalog
      summary: create_category catalog
      operationId: catalog#create_category
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateCategoryRequestBody'
            example:
              name: Doloribus voluptas dicta.
      responses:
        "201":
          description: ""
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CategoryDTO'
              example:
                id: Accusamus repudiandae sed sed maiores qui.
                name: Rem rem.
        "400":
          description: ""
          content:
            application/vnd.goa.error:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                fault: true
                id: 123abc
                message: parameter 'p' must be an integer
                name: bad_request
                temporary: false
                timeout: false
  /categories/{id}:
    get:
      tags:
      - catalog
      summary: show_category catalog
      operationId: catalog#show_category
      parameters:
      - name: id
        in: path
        description: ID
        required: true
        schema:
          type: string
          description: ID
          example: Eius nisi consequatur.
        example: Qui odio dolores.
      responses:
        "200":
          description: ""
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CategoryDTO'
              example:
                id: Ratione facilis corrupti eos consectetur repellat animi.
                name: Tenetur ex corrupti.
        "404":
          description: ""
          content:
            application/vnd.goa.error:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                fault: false
                id: 123abc
                message: parameter 'p' must be an integer
                name: bad_request
                temporary: true
                timeout: true
  /countries:
    post:
      tags:
      - catalog
      summary: create_country catalog
      operationId: catalog#create_country
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateCategoryRequestBody'
            example:
              name: Quaerat cumque.
      responses:
        "201":
          description: ""
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CountryDTO'
              example:
                id: Sit magni itaque.
                name: Assumenda aperiam excepturi harum enim.
                state_ids: Illo recusandae occaecati animi iste.
        "400":
          description: ""
          content:
            application/vnd.goa.error:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                fault: false
                id: 123abc
                message: parameter 'p' must be an integer
                name: bad_request
                temporary: true
                timeout: true
  /coupons:
    post:
      tags:
      - catalog
      summary: create_coupon catalog
      operationId: catalog#create_coupon
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateCouponRequestBody'
            example:
              code: Sit et est atque dolor.
              discount: 0.59967625
              validity: Quo voluptate quidem earum.
      responses:
        "201":
          description: ""
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CouponDTO'
              example:
                code: Fugit corporis aliquid beatae sequi in placeat.
                discount: 0.74422586
                id: Enim doloremque facere.
                validity: Iure voluptatem magnam quia.
        "400":
          description: ""
          content:
            application/vnd.goa.error:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                fault: false
                id: 123abc
                message: parameter 'p' must be an integer
                name: bad_request
                temporary: false
                timeout: true
  /customers:
    post:
      tags:
      - catalog
      summary: create_customer catalog
      operationId: catalog#create_customer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateCustomerRequestBody'
            example:
              address:
                address: Molestiae aut ut.
                cep: Adipisci quas aut quis culpa dolor nam.
                city: Nam facilis.
                complement: Libero consequatur eveniet expedita dolore quod.
                country_id: Libero ut culpa recusandae et rem.
                state_id: Et dolore enim quia est nobis architecto.
              cart_ids:
              - Mollitia rerum ullam.
              - Deserunt error ea tempore minus omnis aspernatur.
              - Ut qui et eius dolore.
              - Deserunt expedita ratione.
              document: Laudantium voluptate quis velit necessitatibus recusandae non.
              email: joy@orn.org
              first_name: At autem dolorem consequatur dicta.
              last_name: Earum et.
              phone: Sit nisi molestiae aliquid nesciunt.
      responses:
        "201":
          description: ""
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CustomerDTO'
              example:
                address:
                  address: Culpa omnis nihil.
                  cep: Itaque necessitatibus voluptatem.
                  city: Enim voluptatem deserunt.
                  complement: Corporis maiores labore autem occaecati eligendi fugit.
                  country_id: Minus quia nobis reprehenderit cupiditate quos.
                  state_id: Aliquid ipsam hic beatae.
                cart_ids:
                - Qui doloremque provident id ut.
                - Omnis perspiciatis et ducimus eaque.
                document: Quaerat corporis harum praesentium consequatur dolor quam.
                email: roger@funk.org
                first_name: Quo sint id adipisci sed sit ullam.
                id: Neque eum et natus.
                last_name: Enim possimus eligendi est.
                phone: Sint dignissimos.
        "400":
          description: ""
          content:
            application/vnd.goa.error:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                fault: true
                id: 123abc
                message: parameter 'p' must be an integer
                name: bad_request
                temporary: true
                timeout: false
  /states:
    post:
      tags:
      - catalog
      summary: create_state catalog
      operationId: catalog#create_state
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateStateRequestBody'
            example:
              country_id: Corporis atque nostrum qui dolor aspernatur.
              name: Eos neque sint qui id.
      responses:
        "201":
          description: ""
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StateDTO'
              example:
                country_id: Enim quo officiis.
                id: Dolores voluptatem.
                name: Non delectus quaerat fugiat facilis.
        "400":
          description: ""
          content:
            application/vnd.goa.error:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                fault: false
                id: 123abc
                message: parameter 'p' must be an integer
                name: bad_request
                temporary: false
                timeout: false
  /swagger.json:
    get:
      tags:
      - swagger
      summary: Download ../../gen/http/openapi.json
      operationId: swagger#/swagger.json
      responses:
        "200":
          description: File downloaded
components:
  schemas:
    ActorDTO:
      type: object
      properties:
        created_at:
          type: string
          example: Ex quam aut optio.
        description:
          type: string
          example: 98w
          maxLength: 400
        email:
          type: string
          example: lavern@sawayn.biz
          format: email
        id:
          type: string
          example: Ea asperiores cupiditate aliquam itaque inventore aperiam.
        name:
          type: string
          example: Cumque numquam qui consequatur ad.
      example:
        created_at: Et dolor recusandae numquam laboriosam suscipit.
        description: ihg
        email: vivien_johns@kutch.name
        id: Illum ea quos.
        name: Sapiente repellat hic est et veniam nihil.
      required:
      - id
      - name
      - email
      - description
      - created_at
    AddressDTO:
      type: object
      properties:
        address:
          type: string
          example: Quo est est dolorum nemo.
        cep:
          type: string
          example: Sed repudiandae iure molestiae.
        city:
          type: string
          example: Quod nostrum quaerat nemo eius.
        complement:
          type: string
          example: Temporibus ab reprehenderit.
        country_id:
          type: string
          example: Perferendis est consequatur at.
        state_id:
          type: string
          example: Laboriosam ipsum architecto qui omnis voluptatem.
      description: Address Type
      example:
        address: Dolor maiores est.
        cep: Qui accusamus asperiores vitae et.
        city: Rem sequi asperiores non labore sit dignissimos.
        complement: Quibusdam ut est iste.
        country_id: Est ipsam impedit molestiae porro.
        state_id: Excepturi assumenda et explicabo sed.
      required:
      - address
      - complement
      - city
      - country_id
      - state_id
      - cep
    BookDTO:
      type: object
      properties:
        actor_ids:
          type: array
          items:
            type: string
            example: Aut expedita.
          example:
          - Autem alias hic ducimus et eveniet.
          - Repudiandae eos dolorem ullam veniam non aut.
          - Illo incidunt quibusdam commodi quasi doloremque.
          - Earum rerum enim tempore qui dolore.
        category_ids:
          type: array
          items:
            type: string
            example: Perferendis nesciunt.
          example:
          - Itaque mollitia porro impedit architecto natus est.
          - Minus debitis nihil labore optio.
          - Voluptatum nulla error natus ut minima.
        id:
          type: string
          example: Nostrum sed eius est velit.
        isbn:
          type: string
          example: Tempora et.
        issue:
          type: string
          example: Non voluptate eos aut.
        pages:
          type: integer
          example: 6941906146793493319
          minimum: 100
        price:
          type: number
          example: 20.862757
          minimum: 20
        summary:
          type: string
          example: Velit provident laboriosam dolore tempore qui.
        synopsis:
          type: string
          example: 3h0
          maxLength: 500
        title:
          type: string
          example: Inventore veniam amet ea eos porro.
      example:
        actor_ids:
        - Omnis velit quidem.
        - Hic consequatur.
        - Vitae totam suscipit et.
        - Aut quidem quisquam.
        category_ids:
        - Aut beatae et pariatur distinctio inventore.
        - Libero doloribus alias ipsa.
        - Deserunt quo fugit rerum quis quaerat repellat.
        id: Deserunt adipisci.
        isbn: Rerum placeat.
        issue: Fuga nobis.
        pages: 8348892686055520885
        price: 20.147593
        summary: Eveniet ex molestiae ducimus in.
        synopsis: oo2
        title: Rerum rerum.
      required:
      - id
      - title
      - synopsis
      - price
      - pages
      - isbn
      - issue
      - category_ids
      - actor_ids
    CartDTO:
      type: object
      properties:
        customer_id:
          type: string
          example: Corporis quam.
        id:
          type: string
          example: Quam repellat qui est.
        items:
          type: array
          items:
            $ref: '#/components/schemas/ItemDTO'
          example:
          - amount: 1496435812
            book_id: Ut doloremque doloremque at nemo pariatur.
          - amount: 1496435812
            book_id: Ut doloremque doloremque at nemo pariatur.
          - amount: 1496435812
            book_id: Ut doloremque doloremque at nemo pariatur.
        total:
          type: number
          example: 0.97122514
          format: float
      example:
        customer_id: Quae aut.
        id: Dolorem consequatur et aut.
        items:
        - amount: 1496435812
          book_id: Ut doloremque doloremque at nemo pariatur.
        - amount: 1496435812
          book_id: Ut doloremque doloremque at nemo pariatur.
        - amount: 1496435812
          book_id: Ut doloremque doloremque at nemo pariatur.
        - amount: 1496435812
          book_id: Ut doloremque doloremque at nemo pariatur.
        total: 0.86912155
      required:
      - id
      - total
      - items
      - customer_id
    CategoryDTO:
      type: object
      properties:
        id:
          type: string
          example: Iusto labore voluptas laborum.
        name:
          type: string
          example: Iure nihil nostrum soluta.
      example:
        id: Officia est.
        name: Optio consequatur.
      required:
      - id
      - name
    CountryDTO:
      type: object
      properties:
        id:
          type: string
          example: Dolorem reprehenderit pariatur voluptatem eum.
        name:
          type: string
          example: Eius ab reiciendis atque et at.
        state_ids:
          type: string
          example: Voluptates dicta nihil a.
      example:
        id: Itaque voluptate.
        name: Sed nemo eius accusantium dolor et libero.
        state_ids: Et quidem totam voluptatum iste nam.
      required:
      - id
      - name
    CouponDTO:
      type: object
      properties:
        code:
          type: string
          example: Sit impedit expedita facilis porro.
        discount:
          type: number
          example: 0.030300518
          minimum: 0
        id:
          type: string
          example: Maiores impedit quod et.
        validity:
          type: string
          example: Id vel ut dolor voluptatem.
      example:
        code: Rerum ut quis expedita vel.
        discount: 0.89822626
        id: Quos repellat iusto hic.
        validity: Veniam ut molestiae temporibus ut voluptatem.
      required:
      - id
      - code
      - discount
      - validity
    CreateActorRequestBody:
      type: object
      properties:
        description:
          type: string
          example: 2tc
          maxLength: 400
        email:
          type: string
          example: diego@baumbach.net
          format: email
        name:
          type: string
          example: Est est et.
      example:
        description: bqj
        email: travon@cummerata.org
        name: Omnis aut est tenetur quibusdam est.
      required:
      - name
      - email
      - description
    CreateBookRequestBody:
      type: object
      properties:
        actor_ids:
          type: array
          items:
            type: string
            example: Consequuntur quia quae ex veniam aut.
          example:
          - Cum est debitis.
          - Totam voluptate ex doloremque.
          - Aut exercitationem ipsam consectetur.
        category_ids:
          type: array
          items:
            type: string
            example: Eum et accusantium.
          example:
          - Sed praesentium velit.
          - Sed maxime reiciendis reprehenderit tempora.
        isbn:
          type: string
          example: Iusto dolores quos provident iure.
        issue:
          type: string
          example: Architecto quibusdam.
        pages:
          type: integer
          example: 1132235040867492842
          minimum: 100
        price:
          type: number
          example: 20.921015
          minimum: 20
        summary:
          type: string
          example: Quia nam.
        synopsis:
          type: string
          example: pc8
          maxLength: 500
        title:
          type: string
          example: Veritatis quis in libero perspiciatis repellat.
      example:
        actor_ids:
        - Molestiae nisi qui iste ut aut vel.
        - Non reiciendis aut et.
        - Sunt perspiciatis eos illum aut amet impedit.
        category_ids:
        - Atque ad eius nihil doloremque recusandae.
        - Nulla dolor inventore facilis quasi optio.
        - Aut qui.
        - Ut facere.
        isbn: Repudiandae consequatur.
        issue: Quasi voluptatem est blanditiis ad.
        pages: 2019419108953976683
        price: 20.803469
        summary: Cupiditate quia.
        synopsis: e2p
        title: Illum consectetur quasi.
      required:
      - title
      - synopsis
      - price
      - pages
      - isbn
      - issue
      - category_ids
      - actor_ids
    CreateCartRequestBody:
      type: object
      properties:
        customer_id:
          type: string
          example: Rerum et eaque rem.
        items:
          type: array
          items:
            $ref: '#/components/schemas/ItemDTO'
          example:
          - amount: 1682166100
            book_id: Occaecati quibusdam non.
          - amount: 1682166100
            book_id: Occaecati quibusdam non.
          - amount: 1682166100
            book_id: Occaecati quibusdam non.
        total:
          type: number
          example: 0.7439847
          format: float
      example:
        customer_id: Aut nulla totam molestias.
        items:
        - amount: 1682166100
          book_id: Occaecati quibusdam non.
        - amount: 1682166100
          book_id: Occaecati quibusdam non.
        - amount: 1682166100
          book_id: Occaecati quibusdam non.
        - amount: 1682166100
          book_id: Occaecati quibusdam non.
        total: 0.2459852
      required:
      - total
      - items
      - customer_id
    CreateCategoryRequestBody:
      type: object
      properties:
        name:
          type: string
          example: Quidem est quo architecto.
      example:
        name: Quae veniam qui et dignissimos.
      required:
      - name
    CreateCouponRequestBody:
      type: object
      properties:
        code:
          type: string
          example: Provident magnam in.
        discount:
          type: number
          example: 0.4003768
          minimum: 0
        validity:
          type: string
          example: Dolore qui recusandae veniam.
      example:
        code: Quibusdam repellendus.
        discount: 0.8712553
        validity: Quos sequi numquam et explicabo.
      required:
      - code
      - discount
      - validity
    CreateCustomerRequestBody:
      type: object
      properties:
        address:
          $ref: '#/components/schemas/AddressDTO'
        cart_ids:
          type: array
          items:
            type: string
            example: Aperiam temporibus.
          example:
          - Minima eius eos omnis.
          - Qui ut repellendus inventore adipisci velit.
          - Totam doloribus debitis enim.
          - Sunt architecto ipsum.
        document:
          type: string
          example: Alias vel consequatur ut dolorem.
        email:
          type: string
          example: kaden_swaniawski@kautzerhyatt.name
          format: email
        first_name:
          type: string
          example: Est sunt qui ratione aperiam labore ad.
        last_name:
          type: string
          example: Aut voluptate quasi deleniti quia sit.
        phone:
          type: string
          example: Nobis numquam maxime vel non.
      example:
        address:
          address: Molestiae aut ut.
          cep: Adipisci quas aut quis culpa dolor nam.
          city: Nam facilis.
          complement: Libero consequatur eveniet expedita dolore quod.
          country_id: Libero ut culpa recusandae et rem.
          state_id: Et dolore enim quia est nobis architecto.
        cart_ids:
        - Ratione ducimus perspiciatis saepe cumque.
        - Dolor deserunt inventore.
        - Totam rerum perspiciatis doloribus consequatur illum.
        document: Quibusdam vitae odio necessitatibus.
        email: einar.bartoletti@rowe.biz
        first_name: Dolor non neque culpa ut.
        last_name: Enim dicta a in quibusdam.
        phone: Natus eligendi.
      required:
      - first_name
      - last_name
      - email
      - document
      - address
      - phone
    CreateStateRequestBody:
      type: object
      properties:
        country_id:
          type: string
          example: Repellat repellat.
        name:
          type: string
          example: Saepe aspernatur repellat fuga aliquid aliquam et.
      example:
        country_id: Dignissimos rerum repellendus omnis.
        name: Dolore ipsa sit nihil.
      required:
      - name
      - country_id
    CustomerDTO:
      type: object
      properties:
        address:
          $ref: '#/components/schemas/AddressDTO'
        cart_ids:
          type: array
          items:
            type: string
            example: Voluptatem ipsum.
          example:
          - Quia voluptas debitis dolorem in id.
          - Commodi eligendi.
        document:
          type: string
          example: Consequatur sint ratione quia quisquam sed ut.
        email:
          type: string
          example: josie@kertzmannsporer.biz
          format: email
        first_name:
          type: string
          example: Sed quis et.
        id:
          type: string
          example: Laborum adipisci.
        last_name:
          type: string
          example: Autem dolorem et.
        phone:
          type: string
          example: Ut et impedit eveniet ut.
      example:
        address:
          address: Culpa omnis nihil.
          cep: Itaque necessitatibus voluptatem.
          city: Enim voluptatem deserunt.
          complement: Corporis maiores labore autem occaecati eligendi fugit.
          country_id: Minus quia nobis reprehenderit cupiditate quos.
          state_id: Aliquid ipsam hic beatae.
        cart_ids:
        - Officiis et quia.
        - Vel eaque.
        - Reprehenderit accusantium tempore sit consequatur quae.
        - Qui veniam est quo reprehenderit.
        document: Fugit in vel voluptate provident cupiditate est.
        email: jamaal@reinger.com
        first_name: Amet ut quos asperiores similique numquam.
        id: Ut et atque error velit aliquam.
        last_name: Nulla corrupti excepturi voluptas est ullam.
        phone: Beatae et maxime id quis.
      required:
      - id
      - first_name
      - last_name
      - email
      - document
      - address
      - phone
    Error:
      type: object
      properties:
        fault:
          type: boolean
          description: Is the error a server-side fault?
          example: true
        id:
          type: string
          description: ID is a unique identifier for this particular occurrence of the problem.
          example: 123abc
        message:
          type: string
          description: Message is a human-readable explanation specific to this occurrence of the problem.
          example: parameter 'p' must be an integer
        name:
          type: string
          description: Name is the name of this class of errors.
          example: bad_request
        temporary:
          type: boolean
          description: Is the error temporary?
          example: true
        timeout:
          type: boolean
          description: Is the error a timeout?
          example: false
      example:
        fault: false
        id: 123abc
        message: parameter 'p' must be an integer
        name: bad_request
        temporary: true
        timeout: false
      required:
      - name
      - id
      - message
      - temporary
      - timeout
      - fault
    ItemDTO:
      type: object
      properties:
        amount:
          type: integer
          example: 216993904
          format: int32
        book_id:
          type: string
          example: Facilis quia eos eum exercitationem.
      description: Item Type
      example:
        amount: 139988390
        book_id: In nam sint non.
      required:
      - book_id
      - amount
    StateDTO:
      type: object
      properties:
        country_id:
          type: string
          example: Nesciunt culpa saepe iste error ut et.
        id:
          type: string
          example: Numquam ipsam autem placeat.
        name:
          type: string
          example: Officia libero provident.
      example:
        country_id: Aliquid est.
        id: Perspiciatis voluptatem eveniet.
        name: Quos ipsam qui.
      required:
      - id
      - name
      - country_id
